[[deployed]]
artifact_name = "chrome-devtools"
artifact_type = "skill"
from_collection = "default"
deployed_at = "2025-11-13T13:49:37.793701"
artifact_path = "skills/chrome-devtools"
collection_sha = "7f34152edc1c794e746156bd574dcb0d4d578bcc704c8f818714e188cee6ddbe"
local_modifications = false
