[[deployed]]
artifact_name = "skillmeat-cli"
artifact_type = "skill"
from_collection = "default"
deployed_at = "2026-01-05T15:07:49.157370"
artifact_path = "skills/skillmeat-cli"
content_hash = "2e7442e246b43330c40e3a09313bc002a3c08b28261f35ac64d1f6a4201944a5"
local_modifications = false
version_lineage = [
    "2e7442e246b43330c40e3a09313bc002a3c08b28261f35ac64d1f6a4201944a5",
]
collection_sha = "2e7442e246b43330c40e3a09313bc002a3c08b28261f35ac64d1f6a4201944a5"

[[deployed]]
artifact_name = "meatycapture-capture"
artifact_type = "skill"
from_collection = "default"
deployed_at = "2026-01-05T15:07:49.158515"
artifact_path = "skills/meatycapture-capture"
content_hash = "735b0aa20026876fcb02379c6f87a48913e6bb7310415ad8dc0c8480db835bb9"
local_modifications = false
version_lineage = [
    "735b0aa20026876fcb02379c6f87a48913e6bb7310415ad8dc0c8480db835bb9",
]
collection_sha = "735b0aa20026876fcb02379c6f87a48913e6bb7310415ad8dc0c8480db835bb9"

[[deployed]]
artifact_name = "Design Principles"
artifact_type = "skill"
from_collection = "default"
deployed_at = "2026-01-09T14:03:41.312919"
artifact_path = "skills/Design Principles"
content_hash = "b399371c92d510b4f1dc7c59489ae4ff44db3bbeff6150d1b3b59baf9698bc06"
local_modifications = false
version_lineage = [
    "b399371c92d510b4f1dc7c59489ae4ff44db3bbeff6150d1b3b59baf9698bc06",
]
merge_base_snapshot = "b399371c92d510b4f1dc7c59489ae4ff44db3bbeff6150d1b3b59baf9698bc06"
collection_sha = "b399371c92d510b4f1dc7c59489ae4ff44db3bbeff6150d1b3b59baf9698bc06"

[[deployed]]
artifact_name = "prd-writer"
artifact_type = "agent"
from_collection = "default"
deployed_at = "2026-01-09T14:32:10.550083"
artifact_path = "agents/pm/prd-writer.md"
content_hash = "4c1dd9d428073f665d9b198c506da53b6337ca7676d80684b7126fae77bf5ff2"
local_modifications = false
version_lineage = [
    "4c1dd9d428073f665d9b198c506da53b6337ca7676d80684b7126fae77bf5ff2",
]
collection_sha = "4c1dd9d428073f665d9b198c506da53b6337ca7676d80684b7126fae77bf5ff2"

[[deployed]]
artifact_name = "aesthetic"
artifact_type = "skill"
from_collection = "default"
deployed_at = "2026-01-10T14:47:36.696010"
artifact_path = "skills/aesthetic"
content_hash = "615241a9b73651094ccfe99f1a3b32ff54f1ba8b90063ec5a6ac3375ddabe36e"
local_modifications = false
merge_base_snapshot = "615241a9b73651094ccfe99f1a3b32ff54f1ba8b90063ec5a6ac3375ddabe36e"
collection_sha = "615241a9b73651094ccfe99f1a3b32ff54f1ba8b90063ec5a6ac3375ddabe36e"
